import os

VECTARA_CUSTOMER_ID = ""
VECTARA_CLIENT_ID = ""
VECTARA_CLIENT_SECRET = ""

os.environ["VECTARA_CUSTOMER_ID"] = VECTARA_CUSTOMER_ID
os.environ["VECTARA_CLIENT_ID"] = VECTARA_CLIENT_ID
os.environ["VECTARA_CLIENT_SECRET"] = VECTARA_CLIENT_SECRET